- name: install loginsight from nexus
  yum:
    name: http://nexus.int.sentania.net:8081/repository/labassets/loginsight/4.5/windows/VMware-Log-Insight-Agent-4.5.0-5626690_10.100.100.80.msi
    state: present
